# .streamlit/secrets.toml
[ldap]
server = "ldap://HOSTNAME:PORT(Default:389)"
#user_dn_template = "uid=%s,ou={OU_NAME},dc={DC_NAME},dc={DC_NAME}"
base_dn = "{OU_NAME},dc={DC_NAME},dc={DC_NAME}"
bind_dn = "cn={admin-user},dc={DC_NAME},dc={DC_NAME}l"
bind_password = "{password}"
[proxmox]
host = "{PROXMOX_HOST_URL}"
user = "root@pam"
password = "{PROXMOX_HOST_PASS}"
verify_ssl = false # 自己署名証明書の場合はfalse
[nodes_mac]
amembo = "{WOL_HOOK_WOL}"
